import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Heading } from '@chakra-ui/react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Heading as='h4' size='lg'  fontSize='40px' noOfLines={4} >hello world</Heading> 
          <Heading as='h1' variant="solid" size='xl'  fontSize='50px' noOfLines={4} >hello world</Heading> 
        </div>
      </main>
    </>
  )
}
